version: "3"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm run devStart
    image: "learning:build"
    environment:
      NODE_ENV: production
      PORT: 3000
      REDIS_URL: 'redis://@redis:6379'
      DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
    volumes:
      - ./:/app/api
    ports:
        - '3000:3000'
    links:
        - redis
        - postgres
  socketserver:
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm run startSocket
    image:  "socket:server"
    environment:
      NODE_ENV: production
      PORT: 4000
      REDIS_URL:  'redis://@redis:6379'
      DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
    volumes:
      - ./:/app/api
    ports:
      - '4000:4000'
    links:
      - redis
      - postgres
      - api
  redis:
    image: redis
    ports:
      - '6379:6379'
  postgres:
    image: postgres
    ports:
      - '5432:5432'

